// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4MUc8WR3uAG3eDDGW7eEtc7730NS37AE',
    appId: '1:1098608666674:web:3f3f8f2ef075e9f8eb742b',
    messagingSenderId: '1098608666674',
    projectId: 'flutterweekend-awladnh-2023',
    authDomain: 'flutterweekend-awladnh-2023.firebaseapp.com',
    storageBucket: 'flutterweekend-awladnh-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBdXsQXDyV6-Fbbg633yqDKL7MslNHmc',
    appId: '1:1098608666674:android:e0a08ad46f5de45beb742b',
    messagingSenderId: '1098608666674',
    projectId: 'flutterweekend-awladnh-2023',
    storageBucket: 'flutterweekend-awladnh-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALjZJzFZXrk7JUO5FhOrW_E_PtNDz7P0c',
    appId: '1:1098608666674:ios:7d42f072a2d7ad76eb742b',
    messagingSenderId: '1098608666674',
    projectId: 'flutterweekend-awladnh-2023',
    storageBucket: 'flutterweekend-awladnh-2023.appspot.com',
    iosBundleId: 'com.example.projectname',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALjZJzFZXrk7JUO5FhOrW_E_PtNDz7P0c',
    appId: '1:1098608666674:ios:4eb3693be3c39248eb742b',
    messagingSenderId: '1098608666674',
    projectId: 'flutterweekend-awladnh-2023',
    storageBucket: 'flutterweekend-awladnh-2023.appspot.com',
    iosBundleId: 'com.example.projectname.RunnerTests',
  );
}
